### ISSUE TITLE
Disqus comments threads not being displayed

### ISSUE THREAD

**Issue by arthur1041** [CaiJimmy/hugo-theme-stack#1041]
### What happened?

# Bug report
Disqus comments thread is not being displayed even after being correctly configured within the config.yaml file.
<img width="960" alt="image" src="https://github.com/user-attachments/assets/ee92005d-fefc-4d60-bb2b-43bbec5afc9f">

# Potential solution
I managed to fix it by copying the content from within `themes/theme-stack/layouts/partials/comments/provider/disqusjs.html` and pasting it inside `themes/theme-stack/layouts/partials/comments/provider/disqus.html`. Now it works fine:
<img width="960" alt="image" src="https://github.com/user-attachments/assets/34972c3c-9f82-46d7-83e6-7a8842a52cf4">

### Hugo version

v0.130.0+extended

### Theme version

3.26.0

### What browsers are you seeing the problem on?

Chrome

### Link to Minimal Reproducible Example

https://github.com/CaiJimmy/hugo-theme-stack/blob/master/layouts/partials/comments/provider/disqus.html ->(my published website doesn't have the error anymore since I fixed it locally)

**Comment by arthur1041** [comment]
Hey, @CaiJimmy. Can you review this PR, please?

**Comment by CaiJimmy** [comment]
Hi Arthur, thanks for the issue report and the pull request. However, I cannot reproduce this issue locally or online. The demo site is built with the latest version of Hugo (0.134.1) and the Disqus comment works fine.

I cannot accept your pull request because it replaces Disqus with Disqus.js, which is a third-party solution that is completely different and requires more setup.

I would guess that your Disqus comment is not showing due to a wrong configuration (e.g. wrong Disqus site name). 

Feel free to reopen this issue if you are able to reproduce this problem online.

**Comment by MuenYu** [comment]
@arthur1041 You should put the `pagenation` part at the bottom of the `config.toml` file. like [this](https://github.com/CaiJimmy/hugo-theme-stack-starter/blob/master/config/_default/config.toml)
