### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by utybo** [CaiJimmy/hugo-theme-stack#129]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

I'd like to be able to add a table of contents to my posts, especially ones that are quite long. It looks like Hugo has [ways of dealing with this for template](https://gohugo.io/content-management/toc/), but I don't see that being used in this template.

**Describe alternatives you've considered**

None?

**Additional context**

This would be especially useful for (very) long posts which would need at least some navigation shortcuts

**Comment by CaiJimmy** [comment]
It was part of the original design. I tried to implement it on the very first version of this theme but it didn't look as I wanted so I dropped it.

![image](https://user-images.githubusercontent.com/5889006/106958566-d5a3a300-6739-11eb-91c5-dbca39ee6488.png)

**It's a planned feature. However, due to the lack of time, I can't say when it will be available.** Probably during this summer vacation.

**Comment by m9810223** [comment]
omg i really need this feature !!!!

**Comment by akuzni2** [comment]
IS there anyway to turn the table of contents  off?

**Comment by utybo** [comment]
Yes, you can set `toc: false` on the post in question
