### ISSUE TITLE
Summary is not show in list of posts if no Description is set

### ISSUE THREAD

**Issue by julian-alarcon** [CaiJimmy/hugo-theme-stack#133]
**Describe the bug**
I will like to use the Summary feature from Hugo but it's not working

**To Reproduce**
1. Leave a post without description, according to the code it should work
2. Check the post list and I see no summary

The code that I check have this
```html
<!-- Use site subtitle by default -->
{{ $description := .Site.Params.sidebar.subtitle }}

{{ if .Description }}
    <!-- Page description exists -->
    {{ $description = .Description }}
{{ else if .IsPage }}
    <!-- Use page summary -->
    {{ $description = .Summary }}
{{ end }}

{{ return ($description | plainify)}}
```
So it should work, but it doesn't 

**Expected behavior**
As no description is defined in the post, the Summary should be show.

**Screenshots**
![image](https://user-images.githubusercontent.com/30119472/106768875-61b6ad00-660a-11eb-9122-0fc289adae7b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser: Firefox/Chrome
Hugo version: 0.80.0 Extended

**Additional context**
Code located here: https://github.com/CaiJimmy/hugo-theme-stack/blob/master/layouts/partials/data/description.html

**Comment by CaiJimmy** [comment]
`/partials/data/description` is only used for generating description for meta tag in `<head>`. For the article card, it's necessary to set manually `description` field in Front Matter.

https://github.com/CaiJimmy/hugo-theme-stack/blob/70cc14fcbe9e229fef7dc2c6a861f1bd6d3c647e/layouts/partials/head/head.html#L4-L5

This behavior is expected. I did this because `.Summary` usually returns a long text (unless you use `<!--more-->` to cut it manually), and I think it doesn't look good.
