### ISSUE TITLE
Image path is incorrect

### ISSUE THREAD

**Issue by ZihaoLin0123** [CaiJimmy/hugo-theme-stack#152]
**Describe the bug**
After I add the image and publish it, I found that in some html files, the path of the images are incorrect.

I add the image to the path "/public/p/deep-learning-1-activation-function/deep-learning-1-activation-function".

After publishing to github, the file was uploaded to the path "https://ZihaoLin0123.github.io/p/deep-learning-1-activation-function/helena-hertz-wWZzXlDpMog-unsplash.jpg". 

However, in some html files, the image path is "p/deep-learning-1-activation-function/helena-hertz-wWZzXlDpMog-unsplash.jpg" which miss the base url. 

How can I fix this?

**Screenshots**

Please see the details here:

![751613951321_ pic_hd](https://user-images.githubusercontent.com/71021979/108642824-72be4580-7475-11eb-8f69-240f2e86cb7b.jpg)

**Comment by CaiJimmy** [comment]
> I add the image to the path "/public/p/deep-learning-1-activation-function/deep-learning-1-activation-function".

I need more information about how you added the featured image. Include the respective Markdown front matter if it's possible.

I deduce that you added the image to `public` folder after the site has been generated. In that case, that's not the correct way to do it, and you should follow the instruction of this page: https://docs.stack.jimmycai.com/writing#add-featured-image

**Comment by eurecomphil** [comment]
I have the same issue.
I have `baseurl: https://myusername.gitlab.io/cooking/`
Since I am using Forestry, when I upload pictures, it puts them in `static/uploads/picture.webp`
In the Front Matter :   
+++
categories = ["sauce"]
date = 2021-02-28T23:00:00Z
description = "Sauce mayonnaise"
**image = "/uploads/mayonnaise.webp"**
+++

However once the website is published, it is trying to find the image under  `https://myusername.gitlab.io/cooking/uploads/mayonnaise.webp` so the URL part `/cooking` has been cut.

If I remove the first `/` in my post MD image path (so **image = "uploads/mayonnaise.webp"**)
It does not work at all, since it will add "uploads/mayonnaise.webp" to the end of the current URL....

I tried to play with `<base href="{{ .Site.BaseURL }}">` but it breaks the website.

Any ideas ??

**Comment by eurecomphil** [comment]
For the Header image, the following helps but it is a bit dirty .... 

In `hugo-theme-stack/layouts/partials/article/components/header.html`, line 28 :
I replaced 
`<img src="{{ $image.permalink }}" loading="lazy" alt="Featured image of post {{ .Title }}" />`  
by
`<img src="{{ .Site.BaseURL }}{{ $image.permalink }}" loading="lazy" alt="Featured image of post {{ .Title }}" />`

**Comment by eurecomphil** [comment]
For the Menu HOME link :  
I replaced 
```
menu:
    main:
        - identifier: home
          name: Home
          url: /
```
By
```
menu:
    main:
        - identifier: home
          name: Home
          url: 
```

**Comment by CaiJimmy** [comment]
> However once the website is published, it is trying to find the image under `https://myusername.gitlab.io/cooking/uploads/mayonnaise.webp` so the URL part /cooking has been cut.

@eurecomphil 
Isn't that how it supposed to behave? I don't understand.

**Comment by CaiJimmy** [comment]
Ok I see what's the issue now.

**Comment by CaiJimmy** [comment]
Should be fixed now. @eurecomphil

**Comment by eurecomphil** [comment]
It is perfect now. 
Thank you for quick answer and your wonderful theme ! :-)
