### ISSUE TITLE
how to change home page(mainSections)?

### ISSUE THREAD

**Issue by eastarpen** [CaiJimmy/hugo-theme-stack#193]
such description exists in official documents

![homepage1](https://user-images.githubusercontent.com/62453776/115024784-25010f00-9ef3-11eb-9029-1c2bda002af3.jpg)

so I want to create a fixed home page for my blog

a directory `home` was created， containing `index.md, home.png`

![dir](https://user-images.githubusercontent.com/62453776/115026279-e2d8cd00-9ef4-11eb-97dc-2cfb6c310073.jpg)

then I changed params mainSections
```
    mainSections: 
        - post
```
to 
```
    mainSections: 
        - home
```
and `hugo server -D`

the home page was empty

![mainSection1](https://user-images.githubusercontent.com/62453776/115026490-23384b00-9ef5-11eb-8a41-c895bacf5e7c.jpg)

then I change `home` to `page`

![mainSection2](https://user-images.githubusercontent.com/62453776/115026581-3fd48300-9ef5-11eb-97f1-ec93fae10086.jpg)

then `page` to `categories`

 ![mainSection3](https://user-images.githubusercontent.com/62453776/115026753-71e5e500-9ef5-11eb-892d-6501d2d94e53.jpg)

why `page` and `post` work, `home`, `categories` doesn't?

and for the description `this/those sections will be shown on homepage and archive page.`

can it be possible that `this/those sections will just be shown on homepage` and `archive page` show `post`  contents?

Thanks for reply!

**Comment by CaiJimmy** [comment]
If I understood correctly, what you are trying to archive is to set **a static homepage**. 

See: https://gohugo.io/templates/homepage/#add-content-and-front-matter-to-the-homepage

**Comment by u-turners** [comment]
Hi Jimmy

Thanks for making such a beautiful theme!
I wanted to follow up on the above question, I followed the link you posted above.

In Hugo it's possible to add content to the _index.md file to be shown on the homepage of the website.
I obviously use your theme.

**How** the content on the homepage is rendered, is defined by the index.html template in theme folder.
I tried to place the {{ .Content }} section in the template - code below correctly, but only with half sucess.

If I add content to my _index.md after the frontmatter it is not rendered correctly in the dark mode of the theme (the letters are in dark instead of white) 

Your index.html tmplate file of your is structured as followed:

```
{{ define "main" }}
    {{ $pages := where .Site.RegularPages "Type" "in" .Site.Params.mainSections }}
    {{ $notHidden := where .Site.RegularPages "Params.hidden" "!=" true }}
    {{ $filtered := ($pages | intersect $notHidden) }}
    {{ $pag := .Paginate ($filtered) }}

    <section class="article-list">
        {{ range $index, $element := $pag.Pages }}
            {{ partial "article-list/default" . }}
        {{ end }}
    </section>

    {{- partial "pagination.html" . -}}
    {{- partial "footer/footer" . -}}
{{ end }}

{{ define "right-sidebar" }}
    {{ partial "sidebar/right.html" (dict "Context" . "Scope" "homepage") }}
{{ end }}
```
Where do I add the {{ .Content }} section correctly, so that the content of _index.md in the root of my content-folder is displayed correctly?

Cheers!

**Comment by eastarpen** [comment]
Hi @[u-turners](https://github.com/u-turners)

I am not sure whether the developer subscribed this issue after it was marked as completed, and sorry I can't help you.

Maybe open a new issue is more appreciate.
