### ISSUE TITLE
Mermaid charts

### ISSUE THREAD

**Issue by sbrandsborg** [CaiJimmy/hugo-theme-stack#220]
Is there any plans including support for Mermaid charts?

https://mermaid-js.github.io/mermaid/#/

**Comment by CaiJimmy** [comment]
> Is there any plans including support for Mermaid charts?

Not yet.

But it doesn't seem hard to be integrated by the user neither, just pasting a snippet of HTML if I have understood it correctly:
![image](https://user-images.githubusercontent.com/5889006/121946746-8ad41080-cd55-11eb-961a-9366b1147072.png)

So I probably won't include this into the theme, unless there are many demands for this feature.

Thanks for the request.

**Comment by ipfans** [comment]
+1 for this.

The official solution is not a very correct choice, if the code is placed into a global page such as footer, it usually leads to pages that all introduce an additional JavaScript file, which is only needed in the posts content. Otherwise, the user may be required to manually inport JavaScript files into each post, which will keep the writers away from focusing on the writings.

**Comment by MikDal002** [comment]
Think about AsciiDoctor instead of Markdown – it has such features (almost) built-in and many others in addition. Here from Hugo doc: https://gohugo.io/content-management/formats/ and here about AsciiDoctor: https://docs.asciidoctor.org/diagram-extension/latest/. If you are familiar with docker, it's the Dockerfile I use for developing blog with those things: 

```dockerfile
FROM asciidoctor/docker-asciidoctor
RUN apk add hugo
```

**Comment by d0zingcat** [comment]
According to [this article](https://gohugo.io/content-management/diagrams/) you can easily do it by yourself. What you need to do is  create one default markup and then copy the article template from hugo-theme-stack and put it in the same level directory in layouts(and the file of the theme will be replaced by this file). BTW, if it doesn't make sense to you so far, you can refer to [this commit](https://github.com/d0zingcat/d0zingcat.github.io/commit/e260447f0adbb899171e7a230860b3d529f761e0). Hope it helps.
