### ISSUE TITLE
jsdelivr.net broken?

### ISSUE THREAD

**Issue by horusra** [CaiJimmy/hugo-theme-stack#238]
Can someone confirm if jsdelivr support is still functional? the theme seems to use jsdelivr.net which is a dead domain, but jsdelivr.com is the actual working cdn.

**Comment by FarrelF** [comment]
> the theme seems to use jsdelivr.net which is a dead domain

No, the `jsdelivr.net` is still alive domain and I can still access `cdn.jsdelivr.net`.

> jsdelivr.com is the actual working CDN

No, the `cdn.jsdelivr.net` is an actual working CDN for jsDelivr, the `jsdelivr.com` domain is only for site front-end purposes. 

If you still cannot access the `cdn.jsdelivr.net` domain, it seems the problem is your ISP or your DNS that cannot resolve jsDelivr CDN domain, or Additional Software (like Antivirus, Firewall, etc)/Browser Add-ons/Features that blocks `cdn.jsdelivr.net` domain or Blocked by a Government or Both.

**Comment by horusra** [comment]
You're right, I think it is being blocked on my end by ISP/DNS.
My bad.
