### ISSUE TITLE
 failed to extract shortcode: template for shortcode "ads" not foundTotal in 23 msError: 

### ISSUE THREAD

**Issue by maidey** [CaiJimmy/hugo-theme-stack#379]
how to fix it?

Error: Error building site: "/home/runner/work/blog/blog/content/post/hilangkan-iklan-di-android/index.md:21:1": failed to extract shortcode: template for shortcode "ads" not found
Total in 23 ms
Error: Process completed with exit code 255.

**Comment by FarrelF** [comment]
Did you make an `ads` shortcode file before? If not, you can create a `layouts/shortcode/ads.html` file in your site folder.

**Comment by maidey** [comment]
yes, but still not working

**Comment by FarrelF** [comment]
> yes, but still not working

Are you sure? Are you create a file named `ads.html` in `layouts/shortcodes` on your site folder before?

If yes, you can check it first and make sure that the file path is correct since I can't check your site source.

**Comment by maidey** [comment]
on localhost it runs smoothly, but after I upload it to github there are a lot of errors

**Comment by FarrelF** [comment]
> on localhost it runs smoothly, but after I upload it to github there are a lot of errors

It could be because Hugo using its cache when running the `hugo server` command by default. If you want a solution for your problem, you must include your source here.

If you don't include your source code here, we can't check what the problem is.

**Comment by maidey** [comment]
OK, wait

**Comment by FarrelF** [comment]
Sorry, I forget something, make sure your site is configurated properly and make sure that you using this theme too.

I suggest checking the value of `theme` in your `config.toml` or `config.yaml` file.

If your theme was in `themes/hugo-theme-stack` directory, you can just fill the `theme` field with `hugo-theme-stack` to using this theme.

**Comment by FarrelF** [comment]
It seems that your problem is solved yet and your site appears properly. Is https://github.com/maidey/maidey.github.io your site source? If yes, let me comment something:

- If you want to create a shortcode, you can just create it in `layouts/shortcodes` under your [Hugo site folder](https://github.com/maidey/maidey.github.io/tree/main/), not in your [Hugo theme folder](https://github.com/maidey/maidey.github.io/tree/main/themes) (e.g. `themes/hugo-theme-stack/layouts/shortcodes` folder)
- If you need to insert a custom code in your site, you can just create `layouts/partials/head/custom.html` or `layouts/partials/head/custom.html` under your Hugo site folder, then insert the code there. You can read the documentation for more: https://docs.stack.jimmycai.com/modify-theme/
- You don't need to fork this theme for just adding a shortcode or modifying the theme. So, you can remove [that repository](https://github.com/maidey/hugo-theme-stack) and use the [original one](https://github.com/CaiJimmy/hugo-theme-stack).
- Create a file named `.nojekyll` in the [root directory](https://github.com/maidey/maidey.github.io/tree/main/) if you are not using Jekyll in GitHub Pages
