### ISSUE TITLE
Add favicon in config.toml

### ISSUE THREAD

**Issue by Arjdroid** [CaiJimmy/hugo-theme-stack#42]
> There is currently no place in the config.toml of the hugo site to specify where to add a favicon file. 

I have found a workaround to this (step-by-step):

1. I made a static/ directory in the directory which contains the source files for the hugo site
2. In the static/ directory I made another directory, in this case, I made it favicon/ 
3. In favicon/ I added the favicon.png file. 
4. Then I went into themes/hugo-theme-stack/layouts/partials/head and modified head.html to include:

```html
<link rel="icon" type="image/png" href="img/favicon.png">
```

I think there could be an easier way to add a favicon; you could perhaps make a toggle in the config.toml file to specify where the favicon should be and then when hugo builds the site it will take that location of the favicon file and automatically include that as the favicon for all the static .html pages.

**Comment by CaiJimmy** [comment]
Hi,

Thanks for the advice. 

This theme's early versions had favicon config included in `config.toml`, but I removed it on the following versions because I thought that pages like [Favicon Generator](https://realfavicongenerator.net/) does much better this job. (It generates resized favicon files, and a snippet of HTML, paste it to `layouts/partials/head/custom.html` and place those images under `static` folder would be enough.)

I agree that adding this option would make this theme be more user-friendly. I'll consider it 👌.
