### ISSUE TITLE
Featured Image Position Adjustment

### ISSUE THREAD

**Issue by zaksquatch** [CaiJimmy/hugo-theme-stack#472]
Hello!

It would be great if there was a sort of toggle we could use to determine where the thumbnail was selected from the feature image. For instance...

- Default behavior could be how it is now, where it seems to cut it from the middle.
- Top would have it cut from the top down.
- Bottom would cut from the bottom up.

I can provide an image example of what I mean if you would like.

**Comment by CaiJimmy** [comment]
If I have understood it correctly, your request is related to this PR: https://github.com/CaiJimmy/hugo-theme-stack/pull/417

However, **that config only applies to thumbnails generated for related content**. The reason is that, in article list (homepage), featured images are generated by invoking the following `resize` function:

https://github.com/CaiJimmy/hugo-theme-stack/blob/6474b9dfd8a5164a191b8aa8f33900e79a2ef0c6/layouts/partials/article/components/header.html#L6-L29

And the `anchor` parameter (where to cut the image), is only supported in `Fill` method: https://gohugo.io/content-management/image-processing/#anchor

**Comment by zaksquatch** [comment]
Yeah, in my research I was seeing that was the case. Thanks for responding though. :)
