### ISSUE TITLE
升级主题之后，生成静态文件时出错partials/sidebar/right.html

### ISSUE THREAD

**Issue by ymkNK** [CaiJimmy/hugo-theme-stack#540]
## Describe the bug
升级主题之后，使用`hugo server`生成静态文件时出错
```
execute of template failed: template: partials/sidebar/right.html:1:33: executing "partials/sidebar/right.html" at <.Scope>: can't evaluate field Scope in type *hugolib.pageState
```
辛苦大佬有空的时候帮忙看一下

## Environment
- **Hugo version** [e.g: 0.80.0]: hugo v0.87.0+extended darwin/amd64 BuildDate=unknown
- **Hugo extended?**: Yes

## Link to the demo site and/or source repository
源仓库地址 https://github.com/ymkNK/hugo

**Comment by ymkNK** [comment]
已修复，由于我本身仓库内index文件已经过时，不适配了，已同步更新适配，已成功更新最新版本 https://lllovol.com/

**Comment by nk9** [comment]
I ran into this error too. The problem ended up being that I had overridden `index.html` and then upgraded to a newer version of the theme which changed the way that [`index.html`](https://github.com/CaiJimmy/hugo-theme-stack/blob/4272da7ee402b43fab957cf328e622279168354c/layouts/index.html#L18) calls the `sidebar/right.html` partial. So instead of this:

```
{{ define "right-sidebar" }}
    {{ partial "sidebar/right.html" . }}
{{ end }}
```

It now needs to look like this:

```
{{ define "right-sidebar" }}
    {{ partial "sidebar/right.html" (dict "Context" . "Scope" "homepage") }}
{{ end }}
```
