### ISSUE TITLE
How to adjust the image crop on the main article list?

### ISSUE THREAD

**Issue by tesujimath** [CaiJimmy/hugo-theme-stack#581]
**Is your feature request related to a problem? Please describe.**
I have many images which look lovely in the single post view, but on the list-of-five main index, they are cropped to letterbox with default centre, and are visually ugly, because the default cropping doesn't match the image.

**Describe the solution you'd like**
It would be really nice to be able to override the image cropping on a per-post basis (in the frontmatter), so that the letterbox images on the main index are visually pleasing. Most often, I would like a different vertical offset.

**Describe alternatives you've considered**
I am really not sure how to do this, sorry.  As far as I can see, the full image is served up and cropped by CSS.

Any ideas as to whether this might be possible?

**Comment by CaiJimmy** [comment]
> It would be really nice to be able to override the image cropping on a per-post basis (in the frontmatter), so that the letterbox images on the main index are visually pleasing. Most often, I would like a different vertical offset.

A brief explanation of what's happening underneath:

On the list-of-five main index, the size of each image is fixed using CSS (full width and height between 150 - 250px depending on the screen size):

https://github.com/CaiJimmy/hugo-theme-stack/blob/0a5cbea10f1ca13fa2f47dae4c6ab4d783ab71ab/assets/scss/partials/article.scss#L21-L35

Since the width is variable (depends on screen size), the theme generates a thumbnail big enough to be rescaled by the browser. The key is the `object-fit` property.

Now, in order to adjust the image offset, we shall use CSS, specifically the property `object-position`: https://developer.mozilla.org/en-US/docs/Web/CSS/object-position

![image](https://user-images.githubusercontent.com/5889006/172156237-14a0eb07-6dd9-4db0-81c9-1cef0bb9893d.png)
![image](https://user-images.githubusercontent.com/5889006/172156260-2bb7c2bc-ec74-450b-b648-c9e31de75100.png)

**So, to archive something similar to #417 , add inline style to `<img>` in this file: https://github.com/CaiJimmy/hugo-theme-stack/blob/master/layouts/partials/article/components/header.html** (Like `style="object-position: {{.Context.Params.image_anchor }}"`)

Now, I won't integrate this feature/configuration in the theme to keep it simple (so I'll close the above PR too). 

If you have any questions still about the implementation just ask here.

**Comment by tesujimath** [comment]
Thanks for the detailed explanation @CaiJimmy really appreciated!

I can understand wanting to keep the theme simple, and `image_anchor` may be too much to include.

Would you be open to a light refactor, so that I can implement this and image_anchor as an override in my own project layouts?  The point is, the unit of override is the file, so I would like to split out a hook from those three layouts so the override is as small as possible.  If you think that might be acceptable to you, I can make a PR before you decide.

**Comment by CaiJimmy** [comment]
Take a look at this: https://github.com/CaiJimmy/hugo-theme-stack/discussions/630

I won't bring any other changes to this theme until the next major version (if it ever comes out).
