### ISSUE TITLE
[Bug]: <kbd> keyword doesn't show keyboard style

### ISSUE THREAD

**Issue by digevil** [CaiJimmy/hugo-theme-stack#803]
### What happened?

`<kbd>` keyword doesn't show keyboard style

it should look like this: <kbd>⇧ Shift</kbd> + <kbd>⌘ Command</kbd> + <kbd>A</kbd>

### Hugo version

v0.111.3+extended darwin/arm64

### Theme version

3.16

### What browsers are you seeing the problem on?

Chrome

### More information about the browser

Chrome 111, MacOS Ventura 13.2, m1 mac air

### Link to the page with bug

https://dev.stack.jimmycai.com/p/markdown-syntax-guide/

### Link to the source repository

https://github.com/CaiJimmy/hugo-theme-stack/blob/master/exampleSite/content/post/markdown-syntax/index.md

**Comment by CaiJimmy** [comment]
Thanks for reporting this issue.

It's because the example site does not have `unsafe` option of Markdown render enabled, so the HTML tags are sanitized:

![image](https://github.com/CaiJimmy/hugo-theme-stack/assets/5889006/424baa1a-b445-4bd2-855c-419e301bdeb0)

But this theme does not have a special style for `kbd` tag either. I'll add this to the log.
