### ISSUE TITLE
Multiline equations with `align` are not displayed correctly

### ISSUE THREAD

**Issue by giovanniberti** [CaiJimmy/hugo-theme-stack#872]
### What happened?

Hi! Thank you for the awesome theme :)

I think I found a bug when layouting multiline equations with the `align*` environment.

For example with this Markdown:

```
$$
\begin{align*}
2x + 1 &= 0 \\
2x + 1 &= 0 
\end{align*}
$$
```

I get this:

![Schermata del 2023-09-01 22-09-48](https://github.com/CaiJimmy/hugo-theme-stack/assets/8624484/7129c400-bcf5-4e56-bc3d-0b90abc8fe77)

While from [KaTeX](https://katex.org/#demo) I get this:
![Schermata del 2023-09-01 22-10-19](https://github.com/CaiJimmy/hugo-theme-stack/assets/8624484/860e4f7c-4ef3-4e89-a2fa-de910b1cd10a)

### Hugo version

hugo v0.116.1+extended

### Theme version

3.19.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### More information about the browser

Linux, Firefox 116, Chrome 109, Not tested on other browsers

### Link to Minimal Reproducible Example

https://github.com/giovanniberti/hugo-theme-stack/tree/align-bug

**Comment by giovanniberti** [comment]
Btw, with the following `raw` shortcode

```
{{ .Inner }}
```
and Markdown

```
{{< raw >}}
$$
\begin{align*}
2x + 1 &= 0 \\
2x + 1 &= 0 
\end{align*}$$
{{< /raw >}}
```

I managed to get the desired result.
Would be nice to not to use a workaround though :)

**Comment by CaiJimmy** [comment]
The reason is because Markdown is escaping backslash.

Instead of `\\`, use `\\\\`.

![image](https://github.com/CaiJimmy/hugo-theme-stack/assets/5889006/1a591353-2e92-49a6-b27d-44cc38ed11a1)
![image](https://github.com/CaiJimmy/hugo-theme-stack/assets/5889006/41308335-ca8b-4142-af16-6635fb79f254)

Your shortcode works because `{{< >}}` skips Markdown rendering:
![image](https://github.com/CaiJimmy/hugo-theme-stack/assets/5889006/ed432580-36bd-4fb6-9240-6ca94505f7a9)
