### ISSUE TITLE
Section's content is not rendered.

### ISSUE THREAD

**Issue by thugcee** [CaiJimmy/hugo-theme-stack#918]
### What happened?

Sometimes section needs some reach text introduction. Currently section content is ignored and only `.Params.description` is displayed.

### Hugo version

0.114.1

### Theme version

3.21.0

### What browsers are you seeing the problem on?

Firefox

### Link to Minimal Reproducible Example

https://github.com/thugcee/jkazs-site/blob/master/content/page/sprawy-klubowe/_index.md

**Comment by CaiJimmy** [comment]
Yes, that's the expected behavior. I wanted the description of a section to be short (1-2 lines) and did not consider the possibility of longer content.

I'd say I'll leave it as it is for now, since it's not something that's widely used. But here's what you need to change to show the full content:

https://github.com/CaiJimmy/hugo-theme-stack/blob/609d43b088c3a8133170466171bcbc3585c3faed/layouts/_default/list.html#L15C1-L17C26

Replace it with `{{ .Content }}`.

Hope this helps and sorry for the late reply.
